stages:
  preprocess:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw_data
    - src/data/make_dataset.py
    outs:
    - data/processed_data
  gridsearch:
    cmd: python src/models/train_gridsearch.py
    deps:
    - data/processed_data
    - src/models/train_gridsearch.py
    outs:
    - models/gridsearch_model.pkl
  trainmodel:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data
    - src/models/train_model.py
    outs:
    - models/trained_model.pkl
